export const FAKE_ROUTE = '#'
export const INDEX_ROUTE = '/'
export const LOGIN_ROUTE = '/login'
export const REGISTER_ROUTE = '/register'
export const USER_PAGE_ROUTE = '/user-page'
export const WATCH_ROUTE = '/watch'
